### ISSUE TITLE
Should check the last byte in Id::from_str

### ISSUE THREAD

**Issue by zensh** [kazk/xid-rs#9]
A bad case:
```rs
let s = "00000000000000jarvis";
assert_eq!(Id::from_str(s).unwrap().to_string().as_str(), s);
```

thread 'id::tests::test_from_str_should_check' panicked at 'assertion failed: `(left == right)`
  left: `"00000000000000jarvig"`,
 right: `"00000000000000jarvis"`'

https://github.com/rs/xid/blob/master/id.go#L267

**Comment by kazk** [comment]
Sorry, I just noticed this. So the original issue is https://github.com/rs/xid/issues/71, and we need to reject invalid strings not generated by xid, which can be done efficiently by [checking the last byte](https://github.com/rs/xid/pull/89).
Thanks, I'll review the PR soon.
